"""empty message

Revision ID: 9529ef4ec6d7
Revises: 8982a216d836
Create Date: 2022-12-18 15:41:30.942200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9529ef4ec6d7'
down_revision = '8982a216d836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('concluida', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.drop_column('concluida')

    # ### end Alembic commands ###
